name: password_wallet
description: "Single-device, on-device encrypted password wallet (starter)"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # state & DI
  get_it: ^8.2.0
  sqflite: ^2.0.0+4 # local DB - placeholder package. For production, integrate SQLCipher native support.
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4  # secure storage (Keychain / Keystore)
  convert: ^3.1.2
  logging: ^1.1.0
  sodium: ^3.4.6
  sodium_libs: ^3.4.6+2
  local_auth: ^3.0.0           # biometric authentication
  local_auth_android: ^2.0.0
  local_auth_darwin: ^2.0.0
  flutter_native_splash: ^2.4.0 # splash screen config
  argon2: ^1.0.1
  path: ^1.8.3
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

